language: python
python:
- '2.6'
branches:
  only:
  - testing
install:
- sh installation.sh
script:
- sh testsuite/travis/test.sh  
env:
  global:
  #usr,pw,gh_token, s3_id&key, gs_id&key, webdav_usr&pwd, webdav2_usr&pwd, webdav3_usr&pwd, webdav4_usr&pwd
  - secure: KlCTerTwn7SZnW8z7wcv0NW2LbVt63HqPddnt6NJEqI0G2VzZbk3HNeWehcll3yPkavE2rQfa58TIN4Tkn03lbDWeTqtPdHD+VR3xkrGhrC672n9YEoM1rgaY5dAmhqbuSXB6EjNwXr/Ry91HtFwC+m0gcvZ1lnnDLoaosV6SYU=
  - secure: cyBcqoKCisTGGsgPp1F04VYdJTu7d3U5ma4ieP2yfFwIlKLSNg2qtZNf7tMAHYm4cz+dpnksVd54LWjA7XHODmMrBRhp4RwhKDo8835hx2q/KAKCkLD79gXwUVE42QqfyLEYAxBpRe3+ASKtJRDOhdVF6f/hK6XSSo5YcEaWQ4w=
  - secure: SQQVDBOVZ1Slwnj1yaEh6gpIM+Pdi03b81k+fl+AWwhmVDB1lTXBb3PPI+V8lvLSN3eia9xUIaVOF5B+/wOWbxwR17plD1mD/sVaZn/GkSJtiKLTr+h7goVcFff2toahtuPYg8IhLnaWgUpB7Xqvr739peloCKBRT1HmNuNf2mg=
  - secure: CAmZUsyhAJAQ00KzeH+/lf7AbFy1sWVatW2XZ06tEfSkK15f3vsEpl1eUPmzadEILx+7l+3HbIDYeo+HkLY1cMlWiXcK8LWhxQ15F2V3SGJz45pP6IMgq4IEKYyAajvpeqoSbvchnP+6zca594sp5vTYT95j0R6IvIcZUva2ZDQ=
  - secure: WjbC1Ys7/YgNy8wdsJHzhWyO2astdbbajJaPbIyqVEisc1jwxbnqXfWUceVqsA7eZJSbWB7CRY7U3Jw3cu5ItZFR0tYLl5RhtT8fLdN4m+h8U4t1DH99zcwE/WLBXTGYzqvBf7GMw/IakE1uqMGfKFUsYxFo+H0V+SJNZ/CRLQI=
  - secure: JOMrU0lpEh7VpfR+34VlHd+vyFUYo/XTxiJ0iMlnaUaVYlbnN3ivH47tdFiokAhrXkzjkU03xEm7OCTndXPAfPo+AFI1yhKMOeBUb4CPcLZsYeaOTvOU783TlpuRVWR9kSB+rV0JocCyOOPUXS1elt1QvqH5XLkwcJJ3BKSuh1A=
  - secure: fzI4SWSSAJ5J0D/XuMqInsuipFJA73jyychB/Q854D/5Bt/8i7G9Gg6W8C4TgbMQWXuU0H0c4BDNT0fOy8hszberEXqAOvkvv/NLiXh0TYdma3/3/l79k2aubRHVurOnZN7lTvh8Fgkzc72sWxp/XPSiZevzoYo02A9X4VGxpNY=
  - secure: ge8SQDgElJiowWWgCuQj0gqfpGRFPuIXWFx0xrXCtR27OqeUsQasv9cHIwXo0hNiF2l8YiDlaJqcX+OQLxt2Uf2caKWuEd0iYCoas7YU0+xCMUVzlcfb6u0HOjxU4ohsnzZk31q5FquWsUdelG+Ar4BS1+SAwjBedSwXGnKL/jA=
  - secure: Ud3JlFbRY5zZZ7Njk0B1NV0jSp91g5P2IuDkjkRWe8RGtdhnYnXr2xZfQMlYQ/N/erqyn2rTYjT3CSGf+3s7525HRqvi9VnJon5oy5QCQ4viWEvGg5BcSra5IVLVPcdTVl9AfT5g475IBpc7QcULUJBgRE7C1nJ6kZvSTPrzjIQ=
  - secure: MXePlDZZ4NmJzCtLS6Ck8gBLJN9zllIAJ/ULvgojqBfzHBDKVZii2AHz/WIBu5gk+8Bs9Fd3BPAsGpWWLaqLyDLyDGO+dP/x4xvp0eOg0A/lLqOaBkGktuCPOyfDVupFZnhgQaAOG09EY5C7j0BCZyX+zF4VMWBWZqa37XqcHSc=
  - secure: cyQmi1UwNYLTI4qFfhREsGyG2hs8MuENitQ+pAZzsq+rzVRLJbyzyRgj+NH8ORNCMJxSe7frvtRo4C6qTGZsB6FSoSh3diN0sxM73PNx6v2q82e1Z9yPPyZVI77e/0WLjHwhIO1aCxzbfTzMkBurfFhVxdA0hQhwJr2fAq+KtCA=
  - secure: Q1L5VcrdYyFxUXWXMDHBzVn4vRTSzTUmH4+ylmYCSHgc9HcbyTM8JcSyOxJ2pDKPN1otj6ShxxoAgeiNk4nioTZRXLpiFan+AlMyPaRcWeGq0OOjYXaR32swYs73BbJAHsSwr69bqTOiIaw3Tm54ETFFUzuy/R+nVZX3Q5Yk+Bk=
  - secure: YVSH7CEgWjUSP1HxY+RIsGKFlIYNOLsDY0F7do+GqiPCa3/iQECAd4FXIPDI4HvFwbVXXCc/jdRKlG84UkyaXmvKD/nBD7sT/PWHVB7LB9zKzGuH7E9PFJeb4GEriH1MHxwDqbbmwJbxxzzJmKiY/nFrVT3Rs530pVB/Y2MaUSE=
  - secure: YgjH2fYk1GIpzyZRT6gqB4NkbgTcT87fmhIXBMahbag/vcL+9hc0uCq4YQ91WHFYikkPj+wmmdCJg6vrUFWyhQPGnbIKzbEnVmxoe3oM5uEX0Bs3nFHtS4Xx94n4W2TLOHb9Kpw0x0w7nzjK3dUPEdPvQmgfzOKAO8ME+u7xqeU=
  - secure: KRWpx0bIDAtSDl6ywg70HsLO58AxknvDxhfsrYrV1LktCVZfLI9ST32ygrTKY2/zlpKOcC3jdhNz7uQZa3A0vEarGqa1vHn7MPYbj7OezR00qftDB1qlIsikz4kA0vZO/npEklHcjNRSwgbBnbdjxxTKRCUnyXFHgliIz1lEcb0=
cache: apt
